-- Developed by Thomas Donofri and Mihai Ficiu https://github.com/donofri/Ned-Flanders-In-Nightmare-Vacation
SelectMission("m0")

SetMissionResetPlayerInCar("m0_ned_car_loc")
SetDynaLoadData("l6z5.p3d;l6r5.p3d;l6r4.p3d;")
UsePedGroup(0)

AddStage()
SetHUDIcon("kburger")
SetStageMessageIndex(02)
AddObjective("goto")
SetDestination("m0_kb","carsphere")
CloseObjective()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetStageMessageIndex(03)
SetHUDIcon("svt")
AddObjective("timer")
SetDurationTime(2)
CloseObjective()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("lundry")
SetStageMessageIndex(04)
AddObjective("goto")
SetDestination("m0_laundry","laundry")
CloseObjective()
AddStageTime(120)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("gas")
SetStageMessageIndex(05)
AddObjective("goto")
SetDestination("m0_gas","carsphere")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("gas")
SetStageMessageIndex(05)
AddObjective("goto")
SetDestination("m0_gas2","triggersphere")
SetFadeOut(0.3)
MustActionTrigger()
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
CloseStage()

AddStage()
--SetStageMessageIndex(03)
--SetHUDIcon("svt")
AddObjective("timer")
SetDurationTime(0.3)
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
CloseStage()

AddStage()
SetStageMessageIndex(01)
AddObjective("getin")
SetObjTargetVehicle("current")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
CloseStage()

AddStage()
--SetHUDIcon("kburger")
SetStageMessageIndex(06)
AddObjective("goto")
SetDestination("m0_aztec","carsphere")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("kburger")
SetStageMessageIndex(07)
AddObjective("goto")
SetDestination("m0_kb2","carsphere")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetStageMessageIndex(08)
SetHUDIcon("svt")
AddObjective("timer")
SetDurationTime(2)
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("kburger")
SetStageMessageIndex(02)
AddObjective("goto")
SetDestination("m0_kb","carsphere")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
--SetHUDIcon("lundry")
SetStageMessageIndex(11)
AddObjective("goto")
SetDestination("m0_meal","kmeal")
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage()
SetStageMessageIndex(09)
SetHUDIcon("svt")
AddObjective("timer")
SetDurationTime(2)
CloseObjective()
AddStageTime(-1)
AddCondition("timeout")
CloseCondition()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

AddStage("final")
--SetHUDIcon("lundry")
SetStageMessageIndex(10)
AddObjective("goto")
SetDestination("m0_motel","carsphere")
CloseObjective()
AddCondition( "damage" )
SetCondMinHealth( 0.0 )
SetCondTargetVehicle( "current" )
CloseCondition()
CloseStage()

CloseMission()