-- Developed by Thomas Donofri and Mihai Ficiu https://github.com/donofri/Ned-Flanders-In-Nightmare-Vacation
SelectMission("m2")

SetMissionResetPlayerInCar("m0_ned_car_loc")
SetDynaLoadData("l6z5.p3d;l6r5.p3d;l6r4.p3d;")

UsePedGroup(6)

AddStage()
SetStageMessageIndex(12)
AddObjective("getin")
SetObjTargetVehicle("current")
CloseObjective()
CloseStage()

AddStage()
SetHUDIcon("klimo")
RESET_TO_HERE()
--SetHUDIcon()
SetStageMessageIndex(01)
AddStageVehicle("cKlimoB","m2_roadblock_1","NULL","Missions\\level06\\M2race.con")
AddStageVehicle("cKlimoC","m2_roadblock_2","NULL","Missions\\level06\\M2race.con")
AddStageVehicle("cKlimo" , "m2_setup","NULL","Chase\\MedChas.con")
AddObjective("goto")
SetDestination("m2_escape","carsphere")
CloseObjective()
if Mode.IsHard then
SetStageTime(10)
else
SetStageTime(15)
end
AddCondition("timeout")
CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("klimo")
SetStageMessageIndex(02)
ActivateVehicle("cKlimo","NULL","chase")
AddObjective("losetail")
SetObjTargetVehicle("cKlimo")
SetObjDistance(155)
CloseObjective()
AddStageTime(60)
	AddCondition( "timeout" )
	CloseCondition()
	AddCondition("outofvehicle")
		SetCondTime( 10000 )
	CloseCondition()
CloseStage()

AddStage()
SetHUDIcon("homer")
SetStageMessageIndex(03)
AddStageVehicle("cKlimoD","m2_klimo_duff","NULL","Destroy\\EasyDest.con")
AddStageVehicle("homer_v","m2_homer_duff","NULL","Missions\\level06\\M2race.con","homer")
AddObjective("goto")
SetDestination("m2_duff","carsphere")
CloseObjective()
CloseStage()

AddStage()
SetHUDIcon("klimo")
AddStageWaypoint("m2_waypoint_1")
AddStageWaypoint("m2_waypoint_2")
AddStageWaypoint("m2_waypoint_3")
AddStageWaypoint("m2_waypoint_1")
ActivateVehicle("cKlimoD","NULL","target")
ActivateVehicle("homer_v","NULL","evade")
SetStageMessageIndex(04)
AddObjective("destroy")
SetObjTargetVehicle("cKlimoD")
CloseObjective()
	AddCondition("followdistance")
		SetFollowDistances(0, 250)
		SetCondTargetVehicle("cKlimoD")
	CloseCondition()
	SetStageTime(120)
AddCondition("timeout")
CloseCondition()
--	SwapInDefaultCar()
	SetSwapDefaultCarLocator("m2_homer_duff")
--	SetSwapForcedCarLocator("m6_canyanaro_sd")
	SetSwapPlayerLocator("m2_ned_duffd")
CloseStage()

AddStage(1)
	AddObjective("timer")
		AddNPC("homer", "m2_hom_duffd")
		StayInBlack()
		SetDurationTime(1)
	CloseObjective()
CloseStage()

AddStage("final")
	AddObjective("dialogue")
		AddNPC("homer", "m2_hom_duffd")
		AmbientAnimationRandomize( 1, 0 )      -- ( pc=0, npc=1) (nonrandom=0, random=1)
		AmbientAnimationRandomize( 0, 0 )
		SetConversationCam( 0, "npc_far" )
		SetConversationCam( 1, "pc_near" )
		SetConversationCam( 2, "npc_far" )
		AddAmbientNpcAnimation( "dialogue_open_arm_hand_gesture" )
		AddAmbientNpcAnimation( "none" )
		AddAmbientNpcAnimation( "dialogue_cross_arms" )
		AddAmbientPcAnimation( "none" )
		AddAmbientPcAnimation( "dialogue_yes" )
		AddAmbientPcAnimation( "none" )
		SetDialogueInfo("ned","homer","duff",0)
--		SetCamBestSide("bestside_m1")
		SetDialoguePositions("m2_hom_duffd","m2_ned_duffd","m2_homer_duff",1)
	CloseObjective()
CloseStage()

CloseMission()